runtime: python39

handlers:
# API routes - handled by Flask app
- url: /api/.*
  script: auto
  secure: always

# Static files for frontend
- url: /(.*\.(css|js|png|jpg|svg|ico|woff|woff2|ttf|eot))$
  static_files: www/\1
  upload: www/.*\.(css|js|png|jpg|svg|ico|woff|woff2|ttf|eot)$
  secure: always

# Frontend routes - serve index.html for SPA routing
- url: /.*
  static_files: www/index.html
  upload: www/index.html
  secure: always

env_variables:
  BUCKET_NAME: recipes-storage-bucket
  GOOGLE_CLOUD_PROJECT: carlkatrin-com
  GOOGLE_CLIENT_ID: YOUR_GOOGLE_CLIENT_ID_HERE